import { Job, Application, Interview, Task } from './types';

// ===== MOCK JOBS DATA =====
export const mockJobs: Job[] = [
    {
        id: 'job-1',
        title: 'Senior Frontend Developer',
        company: 'TechCorp Inc.',
        companyLogo: '🚀',
        location: 'San Francisco, CA',
        locationType: 'Hybrid',
        jobType: 'Full-time',
        salaryMin: 120000,
        salaryMax: 180000,
        salaryCurrency: 'USD',
        description: 'We are looking for an experienced Frontend Developer to join our team.',
        requirements: ['React', 'TypeScript', 'Next.js', '5+ years experience'],
        benefits: ['Health Insurance', '401k', 'Remote Work', 'Unlimited PTO'],
        postedDate: '2025-11-15',
        saved: false,
    },
    {
        id: 'job-2',
        title: 'Full Stack Engineer',
        company: 'StartupXYZ',
        companyLogo: '💡',
        location: 'Remote',
        locationType: 'Remote',
        jobType: 'Full-time',
        salaryMin: 100000,
        salaryMax: 150000,
        salaryCurrency: 'USD',
        description: 'Join our fast-growing startup as a Full Stack Engineer.',
        requirements: ['Node.js', 'React', 'PostgreSQL', '3+ years experience'],
        benefits: ['Equity', 'Health Insurance', 'Flexible Hours'],
        postedDate: '2025-11-18',
        saved: false,
    },
    {
        id: 'job-3',
        title: 'Software Engineer',
        company: 'MegaCorp',
        companyLogo: '🏢',
        location: 'New York, NY',
        locationType: 'On-site',
        jobType: 'Full-time',
        salaryMin: 130000,
        salaryMax: 200000,
        salaryCurrency: 'USD',
        description: 'Looking for talented software engineers to work on cutting-edge projects.',
        requirements: ['Java', 'Spring Boot', 'Microservices', '4+ years experience'],
        benefits: ['Health Insurance', '401k', 'Stock Options', 'Gym Membership'],
        postedDate: '2025-11-10',
        saved: false,
    },
    {
        id: 'job-4',
        title: 'React Developer',
        company: 'WebAgency',
        companyLogo: '🎨',
        location: 'Austin, TX',
        locationType: 'Hybrid',
        jobType: 'Contract',
        salaryMin: 80000,
        salaryMax: 120000,
        salaryCurrency: 'USD',
        description: 'Contract position for an experienced React developer.',
        requirements: ['React', 'Redux', 'CSS', '2+ years experience'],
        benefits: ['Flexible Schedule', 'Remote Options'],
        postedDate: '2025-11-20',
        saved: false,
    },
    {
        id: 'job-5',
        title: 'Backend Developer',
        company: 'DataSystems',
        companyLogo: '📊',
        location: 'Seattle, WA',
        locationType: 'Remote',
        jobType: 'Full-time',
        salaryMin: 110000,
        salaryMax: 160000,
        salaryCurrency: 'USD',
        description: 'Backend developer needed for data-intensive applications.',
        requirements: ['Python', 'Django', 'PostgreSQL', 'AWS', '3+ years experience'],
        benefits: ['Health Insurance', 'Remote Work', '401k', 'Learning Budget'],
        postedDate: '2025-11-12',
        saved: false,
    },
    {
        id: 'job-6',
        title: 'DevOps Engineer',
        company: 'CloudTech',
        companyLogo: '☁️',
        location: 'Boston, MA',
        locationType: 'Hybrid',
        jobType: 'Full-time',
        salaryMin: 125000,
        salaryMax: 175000,
        salaryCurrency: 'USD',
        description: 'DevOps engineer to manage our cloud infrastructure.',
        requirements: ['AWS', 'Kubernetes', 'Docker', 'CI/CD', '4+ years experience'],
        benefits: ['Health Insurance', '401k', 'Stock Options', 'Remote Work'],
        postedDate: '2025-11-08',
        saved: false,
    },
];

// ===== MOCK APPLICATIONS DATA =====
export const mockApplications: Application[] = [
    {
        id: 'app-1',
        jobTitle: 'Senior Frontend Developer',
        company: 'TechCorp Inc.',
        companyLogo: '🚀',
        location: 'San Francisco, CA',
        status: 'Interview',
        appliedDate: '2025-11-10',
        lastUpdated: '2025-11-20',
        salary: '$120k - $180k',
        jobType: 'Full-time',
        priority: 'High',
        notes: 'Really excited about this opportunity. Team seems great!',
        contactPerson: 'Jane Smith',
        contactEmail: 'jane@techcorp.com',
    },
    {
        id: 'app-2',
        jobTitle: 'Full Stack Engineer',
        company: 'StartupXYZ',
        companyLogo: '💡',
        location: 'Remote',
        status: 'Applied',
        appliedDate: '2025-11-18',
        lastUpdated: '2025-11-18',
        salary: '$100k - $150k',
        jobType: 'Full-time',
        priority: 'Medium',
    },
    {
        id: 'app-3',
        jobTitle: 'Software Engineer',
        company: 'MegaCorp',
        companyLogo: '🏢',
        location: 'New York, NY',
        status: 'Phone Screen',
        appliedDate: '2025-11-05',
        lastUpdated: '2025-11-15',
        salary: '$130k - $200k',
        jobType: 'Full-time',
        priority: 'High',
        notes: 'Phone screen scheduled for next week.',
    },
    {
        id: 'app-4',
        jobTitle: 'React Developer',
        company: 'WebAgency',
        companyLogo: '🎨',
        location: 'Austin, TX',
        status: 'Wishlist',
        appliedDate: '2025-11-20',
        lastUpdated: '2025-11-20',
        salary: '$80k - $120k',
        jobType: 'Contract',
        priority: 'Low',
    },
];

// ===== MOCK INTERVIEWS DATA =====
export const mockInterviews: Interview[] = [
    {
        id: 'int-1',
        applicationId: 'app-1',
        company: 'TechCorp Inc.',
        position: 'Senior Frontend Developer',
        type: 'Technical',
        date: '2025-11-25',
        time: '14:00',
        duration: 60,
        meetingLink: 'https://meet.google.com/abc-defg-hij',
        interviewer: 'John Doe',
        interviewerEmail: 'john@techcorp.com',
        notes: 'Prepare for React and TypeScript questions',
        preparation: ['Review React hooks', 'Practice coding challenges', 'Research company'],
        completed: false,
    },
    {
        id: 'int-2',
        applicationId: 'app-3',
        company: 'MegaCorp',
        position: 'Software Engineer',
        type: 'Phone Screen',
        date: '2025-11-23',
        time: '10:00',
        duration: 30,
        interviewer: 'Sarah Johnson',
        notes: 'Initial screening call',
        completed: false,
    },
];

// ===== MOCK TASKS DATA =====
export const mockTasks: Task[] = [
    {
        id: 'task-1',
        title: 'Update resume with latest project',
        description: 'Add the new e-commerce project to resume',
        priority: 'High',
        status: 'Todo',
        dueDate: '2025-11-23',
        createdAt: '2025-11-20',
    },
    {
        id: 'task-2',
        title: 'Prepare for TechCorp interview',
        description: 'Review React concepts and practice coding problems',
        priority: 'High',
        status: 'In Progress',
        dueDate: '2025-11-24',
        relatedTo: {
            type: 'interview',
            id: 'int-1',
            name: 'TechCorp Technical Interview',
        },
        createdAt: '2025-11-18',
    },
    {
        id: 'task-3',
        title: 'Research StartupXYZ company culture',
        description: 'Look into company values and recent news',
        priority: 'Medium',
        status: 'Todo',
        dueDate: '2025-11-25',
        relatedTo: {
            type: 'application',
            id: 'app-2',
            name: 'StartupXYZ Application',
        },
        createdAt: '2025-11-19',
    },
    {
        id: 'task-4',
        title: 'Follow up on MegaCorp application',
        description: 'Send thank you email after phone screen',
        priority: 'Medium',
        status: 'Todo',
        dueDate: '2025-11-24',
        relatedTo: {
            type: 'application',
            id: 'app-3',
            name: 'MegaCorp Application',
        },
        createdAt: '2025-11-21',
    },
    {
        id: 'task-5',
        title: 'Update LinkedIn profile',
        description: 'Add new skills and update headline',
        priority: 'Low',
        status: 'Done',
        createdAt: '2025-11-15',
        completedAt: '2025-11-17',
    },
];
